defaults:
  db_host: localhost
  db_port: 5432
  db_name: postgres

sources:
  - name: spotify_tracks
    type: csv
    path: data/spotify-tracks-dataset.csv
    target_table: stg_tracks
    pk: track_id
    rules:
      - rule: "popularity >= 0 AND popularity <= 100"
      - rule: "track_id NOT NULL"
      - rule: "track_name NOT NULL"

  - name: musicbrainz_artists
    type: api
    url: https://musicbrainz.org/ws/2/artist/
    target_table: stg_artists
    pk: id
    query: Drake
    rules:
      - rule: "id NOT NULL"
      - rule: "name NOT NULL"